#!/usr/bin/env just --justfile
FILENAME := "guia-de-autodiagnostico"
PANDOC_OPTIONS := "--number-sections -C --metadata title='Guía de autodiagnóstico de autismo para documentación y autoanálisis.'"
PANDOC_DOCX_OPTIONS := ""
PANDOC_EPUB_OPTIONS := "--standalone --top-level-division=chapter"
PANDOC_TXT_OPTIONS := ""
PANDOC_PDF_OPTIONS := "-s --pdf-engine=lualatex -L latex-emoji.lua --metadata-file=metadata.yaml -V links-as-notes=true -V colorlinks -V urlcolor=NavyBlue -V mainfont='DejaVu Sans'"
FROM := "gfm"


default: (all "FILE")

docx FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_DOCX_OPTIONS}} --from {{FROM}} --to docx -o {{FILENAME}}.docx {{absolute_path(FILE)}}

txt FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_TXT_OPTIONS}} --from {{FROM}} --to plain -o {{FILENAME}}.txt {{absolute_path(FILE)}}

epub FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_EPUB_OPTIONS}} --from {{FROM}} --to epub3 -o {{FILENAME}}.epub  {{absolute_path(FILE)}}

pdf FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_PDF_OPTIONS}} --from {{FROM}} -o {{FILENAME}}.pdf {{absolute_path(FILE)}}

all FILE:
    just docx {{FILE}}
    just txt {{FILE}}
    just epub {{FILE}}
    just pdf {{FILE}}
