#!/usr/bin/env just --justfile
NAME:="guia-de-autodiagnostico"
PANDOC_OPTIONS := "--number-sections -C"
PANDOC_DOCX_OPTIONS := ""
PANDOC_EPUB_OPTIONS := "--standalone --top-level-division=chapter"
PANDOC_TXT_OPTIONS := ""
PANDOC_PDF_OPTIONS := "-s --pdf-engine=xelatex -V geometry:margin=.4in --toc"
FROM := "gfm"


default: (all "FILE")

docx FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_DOCX_OPTIONS}} --from {{FROM}} --to docx -o {{NAME}}.docx {{absolute_path(FILE)}}

txt FILE:
    pandoc {{PANDOC_OPTIONS}} --from {{FROM}} --to plain -o {{NAME}}.txt {{absolute_path(FILE)}}

epub FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_EPUB_OPTIONS}} --from {{FROM}} --to epub3 -o {{NAME}}.epub {{absolute_path(FILE)}} --metadata title={{file_stem(FILE)}}

pdf FILE:
    pandoc {{absolute_path(FILE)}} -fgfm -o {{NAME}}.pdf {{PANDOC_PDF_OPTIONS}} --metadata title={{file_stem(FILE)}}

all FILE:
    just docx {{FILE}}
    just txt {{FILE}}
    just epub {{FILE}}
    just pdf {{FILE}}
