#!/usr/bin/env just --justfile
NAME:="guia-de-autodiagnostico"
TITLE:="Guía de autodiagnóstico de autismo para documentación y autoanálisis."
PANDOC_OPTIONS := "--number-sections -C"
PANDOC_DOCX_OPTIONS := ""
PANDOC_EPUB_OPTIONS := "--standalone --top-level-division=chapter"
PANDOC_TXT_OPTIONS := ""
PANDOC_PDF_OPTIONS := "-s --pdf-engine=lualatex -L latex-emoji.lua --metadata-file=metadata.yaml -V geometry:margin=.4in -V links-as-notes=true -V colorlinks -V urlcolor=NavyBlue -V mainfont='DejaVu Sans'"
FROM := "gfm"


default: (all "FILE")

docx FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_DOCX_OPTIONS}} --from {{FROM}} --to docx -o {{NAME}}.docx {{absolute_path(FILE)}}

txt FILE:
    pandoc {{PANDOC_OPTIONS}} --from {{FROM}} --to plain -o {{NAME}}.txt {{absolute_path(FILE)}}

epub FILE:
    pandoc {{PANDOC_OPTIONS}} {{PANDOC_EPUB_OPTIONS}} --from {{FROM}} --to epub3 -o {{NAME}}.epub {{absolute_path(FILE)}} --metadata title="{{TITLE}}"

pdf FILE:
    pandoc {{PANDOC_OPTIONS}} {{absolute_path(FILE)}} -f markdown+emoji -o {{NAME}}.pdf {{PANDOC_PDF_OPTIONS}} --metadata title="{{TITLE}}"

all FILE:
    just docx {{FILE}}
    just txt {{FILE}}
    just epub {{FILE}}
    just pdf {{FILE}}
